---
- name: Get PRTG Device IDs
  hosts: localhost
  gather_facts: false
  vars:
    prtg_api_url: "https://prtg.example.com/api"
    prtg_api_token: "your_prtg_api_token"
    hostnames:
      - hostname1
      - hostname2
      - hostname3
  tasks:
    - name: Ensure vars directory exists
      ansible.builtin.file:
        path: vars
        state: directory

    - name: Initialize device_ids dictionary
      set_fact:
        device_ids: {}

    - name: Get PRTG device ID for each hostname
      vars:
        hostname: "{{ item }}"
      ansible.builtin.uri:
        url: "{{ prtg_api_url }}/table.json?content=devices&output=json&columns=device,host&id=0&username=api&passhash={{ prtg_api_token }}"
        method: GET
        return_content: yes
      register: prtg_response
      loop: "{{ hostnames }}"
      changed_when: false

    - name: Parse and store device IDs
      set_fact:
        device_ids: "{{ device_ids | combine({ item: (prtg_response.json.devices | selectattr('host', 'equalto', item) | first).objid }) }}"
      loop: "{{ hostnames }}"
      when: prtg_response.json.devices is defined and (prtg_response.json.devices | selectattr('host', 'equalto', item) | list) | length > 0

    - name: Save device IDs to vars file
      copy:
        content: "{{ device_ids | to_nice_yaml }}"
        dest: vars/device_ids.yml
