name 'ping-allow'
maintainer 'Travis Wade'
maintainer_email 'travis@twade.io'
license 'All Rights Reserved'
description 'Installs/Configures ping allow rules for Windows and Linux'
version '0.1.0'
chef_version '>= 14.0'

supports 'windows'
supports 'ubuntu'
supports 'centos'