AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation Template to enable AWS Systems Manager capabilities for all existing EC2 instances.

Resources:
  SSMIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      RoleName: SSMIAMRole

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref SSMIAMRole
      InstanceProfileName: SSMInstanceProfile

Outputs:
  SSMIAMRole:
    Description: IAM Role for SSM
    Value: !Ref SSMIAMRole
  SSMInstanceProfile:
    Description: Instance Profile for SSM
    Value: !Ref SSMInstanceProfile
