---
- name: Install all available updates
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: installed
  register: update_result

- name: Reboot if updates were installed and require a reboot
  ansible.windows.win_reboot:
  when: update_result.reboot_required
